### ISSUE TITLE
Bundle not compatible with symfony 3.3 anymore

### ISSUE THREAD

**Issue by pandix211** [IDCI-Consulting/AssetLoaderBundle#8]
With the release 2.1.1 your bundle is no more compatible with Symfony 3.3 or any version prior to Symfony 4.1.

You used the [getRootNode method from the TreeView class](https://github.com/IDCI-Consulting/AssetLoaderBundle/commit/2f68ade9303e08c03e908d6a0b64cfa99676094c), but this method have been implemented in in symfony 4.2 and is not available in [symfony 4.1](https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Config/Definition/Builder/TreeBuilder.php) and older.

The composer.json file still indicate "symfony/...": "^3.3|^4.0" wich is no more true.

Can you please rename the tag to a major version or recreate the tag with the composer.json updated ?

**Comment by burahimu** [comment]
Hi @pandix211 

It seems to be fixed with #9 

Thanks :+1:
